### ISSUE TITLE
Update gives stockpile issues.

### ISSUE THREAD

**Issue by chrispikula** [emipa606/ClothingSorter#13]
Not sure why, but with this update, I am unable to look at a fair number of apparel.  I can't figure out _why_, but I do know it's not universal, nor is it just modded apparel.  Different sorting methods don't seem to make a difference either.  It is limited to apparel, and depends if the sub-section is open or closed.  Likewise, when using the stockpile searchbar, errors immediately appear.

Removing this mod, makes the issue go away.  

https://pastebin.com/psjHnqkk

The 'pushing too many gui clips' just goes on forever, afterwards, as long as the menu is open.

**Comment by emipa606** [comment]
@hhyzbd Is this related to your fixes?

**Comment by emipa606** [comment]
Found the issue, the last updates bug-fix caused the apparel categories not to be created when Royalty was active.
Should be fixed in 70fe403
